### ISSUE TITLE
Error rosrun rc_cloud_accumulator segmentation fault

### ISSUE THREAD

**Issue by mitdo** [roboception/rc_cloud_accumulator#4]
I installed ros-melodic-desktop-full=1.4.1-0* with docker based on the the docker image: "nvidia/cuda:9.2-base-ubuntu18.04". 

The camera is working properly. RVIZ is also showing disparity, confidence image and the point cloud.

I installed the cloud_accumulator with "apt-get install ros-melodic-rc-cloud-accumulator"

Starting the node with rosrun "rc_cloud_accumulator rc_cloud_accumulator" brings following error: 

[ INFO] [1617806678.053646966]: Distance filter range: 0.00m - 5.00m
[ INFO] [1617806678.054638319]: Voxel grid filter for display: 0.050m
[ INFO] [1617806678.054661168]: Voxel grid filter for saving:  0.010m
Segmentation fault (core dumped)

my other installed packages: 
-     ros-melodic-rc-visard 
-     ros-melodic-rc-hand-eye-calibration-client 
-     ros-melodic-rc-visard-driver 
-     ros-melodic-rc-common-msgs

the camera is started with "rosrun rc_visard_driver rc_visard_driver _enable_tf:=True _autostart_dynamics:=True _autostop_dynamics:=True _ptp_enabled:=True _autopublish_trajectory:=True"

**Comment by flixr** [comment]
I cannot reproduce the problem on Ubuntu 18.04 directly...
Might be it has something to do with the CUDA base image?

**Comment by mitdo** [comment]
I actually installed cuda base image: nvidia/cuda:9.2-base-ubuntu18.04
( I also tried version 11.2.2) from https://hub.docker.com/r/nvidia/cuda/tags?page=1&ordering=last_updated&name=18.04 


My DockerFile: 
```
FROM nvidia/cuda:9.2-base-ubuntu18.04
RUN apt-get update && apt-get install -y --no-install-recommends \
        sudo \
        vim \
        gnupg2 \
        lsb-release \
        build-essential \
        cuda-command-line-tools-9-2 \
        cuda-cublas-dev-9-2 \
        cuda-cudart-dev-9-2 \
        cuda-cufft-dev-9-2 \
        cuda-curand-dev-9-2 \
        cuda-cusolver-dev-9-2 \
        cuda-cusparse-dev-9-2 \
        curl \
        git \
        libcudnn7=7.1.4.18-1+cuda9.2 \
        libcudnn7-dev=7.1.4.18-1+cuda9.2 \
        libcurl3-dev \
        libfreetype6-dev \
        libhdf5-serial-dev \
        libpng-dev \
        libzmq3-dev \
        pkg-config \
        rsync \
        software-properties-common \
        unzip \
        zip \
        zlib1g-dev \
        wget \
        && \
    rm -rf /var/lib/apt/lists/* && \
    find /usr/local/cuda-9.2/lib64/ -type f -name 'lib*_static.a' -not -name 'libcudart_static.a' -delete && \
    rm /usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

# Configure the build for our CUDA configuration.
ENV CI_BUILD_PYTHON python
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
ENV TF_NEED_CUDA 1
ENV TF_CUDA_COMPUTE_CAPABILITIES=3.0,3.5,5.2,6.0,6.1
ENV TF_CUDA_VERSION=9.2
ENV TF_CUDNN_VERSION=7


# setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN apt-get update && apt-get install -y \
    python \
    python-pip

RUN pip --no-cache-dir install --upgrade \
    pip \
    setuptools

#RUN ln -s $(which ${PYTHON}) /usr/local/bin/python

RUN apt-get update && apt-get install -y \
    openjdk-8-jdk \
    python-dev \
    swig

#########################
##   ROS    ##
#########################

ENV ROS_MASTER_URI http://localhost:11311

# setup timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && \
    apt-get install -q -y --no-install-recommends tzdata && \
    rm -rf /var/lib/apt/lists/*

# install packages
RUN apt-get update && apt-get install -q -y --no-install-recommends \
    dirmngr \
    gnupg2 \
    && rm -rf /var/lib/apt/lists/*

# setup keys
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

# setup sources.list
RUN echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros1-latest.list

# setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

ENV ROS_DISTRO melodic

# install ros packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-melodic-ros-core=1.4.1-0* \
    && rm -rf /var/lib/apt/lists/*

# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    python-rosdep \
    python-rosinstall \
    python-vcstools \
    && rm -rf /var/lib/apt/lists/*

# bootstrap rosdep
RUN rosdep init && \
    rosdep update --rosdistro $ROS_DISTRO

# install ros packages - robot
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-melodic-robot=1.4.1-0* \
    && rm -rf /var/lib/apt/lists/*

# install ros packages - perception
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-melodic-perception=1.4.1-0* \
    && rm -rf /var/lib/apt/lists/*

# install ros packages - desktop
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-melodic-desktop=1.4.1-0* \
    && rm -rf /var/lib/apt/lists/*

# install ros packages - desktop full
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-melodic-desktop-full=1.4.1-0* \
    && rm -rf /var/lib/apt/lists/*

#Other Packages
#.....

## RC-visard
RUN apt-get update && apt-get install -y ros-melodic-rc-visard \
    ros-melodic-rc-hand-eye-calibration-client \
    ros-melodic-rc-visard-driver \
    ros-melodic-rc-common-msgs \
    ros-melodic-rc-cloud-accumulator
```
##################################################
 My docker-compose.yml file
```
version: "2.4"

services:
  melodic:
    hostname: melodic
    runtime: ${DOCKER_RUNTIME}
    privileged: true
    environment:
      # Pass host user information.
      - HOST_USER=${USER}
      - HOST_UID=1000
      - HOST_GID=1000
      # Display X Server GUI.
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      # Configure Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=9.0
    build:
      context: ../
      dockerfile: ./docker/dockerfile
    volumes:
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    network_mode: host
    extra_hosts:
      - "melodic:127.0.0.1"
      - "melodic:192.168.137.201"
```
